# config.yaml

# This section defines the models that your local proxy will advertise.
model_list:
  - model_name: kimi-k2  # The name your local client will use
    litellm_params:
      model: openrouter/moonshotai/kimi-k2 # The actual model name on OpenRouter
      supports_function_calling: true 
      supports_tool_choice: true
      supports_parallel_function_calling: true
      supports_streaming: true
      supports_chat: true
  - model_name: grok-4
    litellm_params:
      model: openrouter/x-ai/grok-4 # The actual model name on OpenRouter
      supports_function_calling: true 
      supports_tool_choice: true
      supports_parallel_function_calling: true
      supports_streaming: true
      supports_chat: true

# This section sets general settings, like your API keys.
litellm_settings:
  # Sets the OpenRouter API key from an environment variable
  # You need to set this environment variable in your terminal
  api_key: os.environ/OPENROUTER_API_KEY
